//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIIntegration.CONNECT {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd", ConfigurationName="CONNECT.HumanResourcesInboundServiceSoap")]
    public interface HumanResourcesInboundServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://northgate-is.com/gem/generic/humanResources/1.0/201203/savePersonnel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIIntegration.CONNECT.savePersonnelResponse savePersonnel(APIIntegration.CONNECT.savePersonnelRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://northgate-is.com/gem/generic/humanResources/1.0/201203/savePersonnel", ReplyAction="*")]
        System.Threading.Tasks.Task<APIIntegration.CONNECT.savePersonnelResponse> savePersonnelAsync(APIIntegration.CONNECT.savePersonnelRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd")]
    public partial class PersonnelRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RecordOperationEnum recordStatusField;
        
        private ConstrainedValue forceIDField;
        
        private string personnelIDField;
        
        private string uniqueNationalIdentifierField;
        
        private string collarNumberField;
        
        private string pncUserIDField;
        
        private ConstrainedValue titleField;
        
        private string surnameField;
        
        private string forename1Field;
        
        private string forename2Field;
        
        private string forename3Field;
        
        private ConstrainedValue genderField;
        
        private supervisor supervisorField;
        
        private string stationNameField;
        
        private string stationCodeField;
        
        private string emailAddressField;
        
        private EmploymentRecord[] employmentHistoryField;
        
        private ConstrainedValue defaultUnitField;
        
        private ConstrainedValue defaultSubmitUnitField;
        
        private UnitRole[] currentUnitsField;
        
        private System.Xml.XmlElement extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RecordOperationEnum recordStatus {
            get {
                return this.recordStatusField;
            }
            set {
                this.recordStatusField = value;
                this.RaisePropertyChanged("recordStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ConstrainedValue forceID {
            get {
                return this.forceIDField;
            }
            set {
                this.forceIDField = value;
                this.RaisePropertyChanged("forceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string personnelID {
            get {
                return this.personnelIDField;
            }
            set {
                this.personnelIDField = value;
                this.RaisePropertyChanged("personnelID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string uniqueNationalIdentifier {
            get {
                return this.uniqueNationalIdentifierField;
            }
            set {
                this.uniqueNationalIdentifierField = value;
                this.RaisePropertyChanged("uniqueNationalIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string collarNumber {
            get {
                return this.collarNumberField;
            }
            set {
                this.collarNumberField = value;
                this.RaisePropertyChanged("collarNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string pncUserID {
            get {
                return this.pncUserIDField;
            }
            set {
                this.pncUserIDField = value;
                this.RaisePropertyChanged("pncUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ConstrainedValue title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string forename1 {
            get {
                return this.forename1Field;
            }
            set {
                this.forename1Field = value;
                this.RaisePropertyChanged("forename1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string forename2 {
            get {
                return this.forename2Field;
            }
            set {
                this.forename2Field = value;
                this.RaisePropertyChanged("forename2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string forename3 {
            get {
                return this.forename3Field;
            }
            set {
                this.forename3Field = value;
                this.RaisePropertyChanged("forename3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public ConstrainedValue gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public supervisor supervisor {
            get {
                return this.supervisorField;
            }
            set {
                this.supervisorField = value;
                this.RaisePropertyChanged("supervisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string stationName {
            get {
                return this.stationNameField;
            }
            set {
                this.stationNameField = value;
                this.RaisePropertyChanged("stationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string stationCode {
            get {
                return this.stationCodeField;
            }
            set {
                this.stationCodeField = value;
                this.RaisePropertyChanged("stationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("emailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute("employment")]
        public EmploymentRecord[] employmentHistory {
            get {
                return this.employmentHistoryField;
            }
            set {
                this.employmentHistoryField = value;
                this.RaisePropertyChanged("employmentHistory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public ConstrainedValue defaultUnit {
            get {
                return this.defaultUnitField;
            }
            set {
                this.defaultUnitField = value;
                this.RaisePropertyChanged("defaultUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public ConstrainedValue defaultSubmitUnit {
            get {
                return this.defaultSubmitUnitField;
            }
            set {
                this.defaultSubmitUnitField = value;
                this.RaisePropertyChanged("defaultSubmitUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=19)]
        [System.Xml.Serialization.XmlArrayItemAttribute("currentUnit")]
        public UnitRole[] currentUnits {
            get {
                return this.currentUnitsField;
            }
            set {
                this.currentUnitsField = value;
                this.RaisePropertyChanged("currentUnits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public System.Xml.XmlElement extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd")]
    public enum RecordOperationEnum {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Amend,
        
        /// <remarks/>
        Archive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://northgate-is.com/gem/generic-common/1.0/201201/common.xsd")]
    public partial class ConstrainedValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cvCodeField;
        
        private string descriptionField;
        
        private System.Xml.XmlElement extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cvCode {
            get {
                return this.cvCodeField;
            }
            set {
                this.cvCodeField = value;
                this.RaisePropertyChanged("cvCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Xml.XmlElement extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd")]
    public partial class SaveStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SaveOperationEnum statusField;
        
        private string errorReasonField;
        
        private ConstrainedValue forceIDField;
        
        private string personnelIDField;
        
        private string uniqueNationalIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SaveOperationEnum status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorReason {
            get {
                return this.errorReasonField;
            }
            set {
                this.errorReasonField = value;
                this.RaisePropertyChanged("errorReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ConstrainedValue forceID {
            get {
                return this.forceIDField;
            }
            set {
                this.forceIDField = value;
                this.RaisePropertyChanged("forceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string personnelID {
            get {
                return this.personnelIDField;
            }
            set {
                this.personnelIDField = value;
                this.RaisePropertyChanged("personnelID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string uniqueNationalIdentifier {
            get {
                return this.uniqueNationalIdentifierField;
            }
            set {
                this.uniqueNationalIdentifierField = value;
                this.RaisePropertyChanged("uniqueNationalIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd")]
    public enum SaveOperationEnum {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OK-RecordCreated")]
        OKRecordCreated,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OK-RecordUpdated")]
        OKRecordUpdated,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OK-RecordArchived")]
        OKRecordArchived,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Error-Duplicate")]
        ErrorDuplicate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Error-InvalidData")]
        ErrorInvalidData,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Error-InvalidPersonnelID")]
        ErrorInvalidPersonnelID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Error-InvalidForceCode")]
        ErrorInvalidForceCode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd")]
    public partial class UnitRole : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConstrainedValue unitField;
        
        private ConstrainedValue roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ConstrainedValue unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ConstrainedValue role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("role");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd")]
    public partial class EmploymentRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        private ConstrainedValue rankField;
        
        private System.Xml.XmlElement extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("from");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toSpecified {
            get {
                return this.toFieldSpecified;
            }
            set {
                this.toFieldSpecified = value;
                this.RaisePropertyChanged("toSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ConstrainedValue rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("rank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Xml.XmlElement extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd")]
    public partial class supervisor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fullNameField;
        
        private ConstrainedValue forceIDField;
        
        private string personnelIDField;
        
        private string uniqueNationalIdentifierField;
        
        private System.Xml.XmlElement extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("fullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ConstrainedValue forceID {
            get {
                return this.forceIDField;
            }
            set {
                this.forceIDField = value;
                this.RaisePropertyChanged("forceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string personnelID {
            get {
                return this.personnelIDField;
            }
            set {
                this.personnelIDField = value;
                this.RaisePropertyChanged("personnelID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string uniqueNationalIdentifier {
            get {
                return this.uniqueNationalIdentifierField;
            }
            set {
                this.uniqueNationalIdentifierField = value;
                this.RaisePropertyChanged("uniqueNationalIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.Xml.XmlElement extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd")]
    public enum SavePersonnelResponseStatusEnum {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Warning-SomeInvalidRecords")]
        WarningSomeInvalidRecords,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="savePersonnel", WrapperNamespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd", IsWrapped=true)]
    public partial class savePersonnelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("personnelRecord")]
        public APIIntegration.CONNECT.PersonnelRecord[] personnelRecords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd", Order=1)]
        public System.Xml.XmlElement extension;
        
        public savePersonnelRequest() {
        }
        
        public savePersonnelRequest(APIIntegration.CONNECT.PersonnelRecord[] personnelRecords, System.Xml.XmlElement extension) {
            this.personnelRecords = personnelRecords;
            this.extension = extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="savePersonnelResponse", WrapperNamespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd", IsWrapped=true)]
    public partial class savePersonnelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd", Order=0)]
        public APIIntegration.CONNECT.SavePersonnelResponseStatusEnum savePersonnelResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd", Order=1)]
        public System.Xml.XmlElement extension;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://northgate-is.com/gem/generic/humanResources/1.0/201203/humanResources.xsd", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("saveStatus")]
        public APIIntegration.CONNECT.SaveStatus[] saveStatusList;
        
        public savePersonnelResponse() {
        }
        
        public savePersonnelResponse(APIIntegration.CONNECT.SavePersonnelResponseStatusEnum savePersonnelResult, System.Xml.XmlElement extension, APIIntegration.CONNECT.SaveStatus[] saveStatusList) {
            this.savePersonnelResult = savePersonnelResult;
            this.extension = extension;
            this.saveStatusList = saveStatusList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HumanResourcesInboundServiceSoapChannel : APIIntegration.CONNECT.HumanResourcesInboundServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HumanResourcesInboundServiceSoapClient : System.ServiceModel.ClientBase<APIIntegration.CONNECT.HumanResourcesInboundServiceSoap>, APIIntegration.CONNECT.HumanResourcesInboundServiceSoap {
        
        public HumanResourcesInboundServiceSoapClient() {
        }
        
        public HumanResourcesInboundServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HumanResourcesInboundServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HumanResourcesInboundServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HumanResourcesInboundServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIIntegration.CONNECT.savePersonnelResponse APIIntegration.CONNECT.HumanResourcesInboundServiceSoap.savePersonnel(APIIntegration.CONNECT.savePersonnelRequest request) {
            return base.Channel.savePersonnel(request);
        }
        
        public APIIntegration.CONNECT.SavePersonnelResponseStatusEnum savePersonnel(APIIntegration.CONNECT.PersonnelRecord[] personnelRecords, ref System.Xml.XmlElement extension, out APIIntegration.CONNECT.SaveStatus[] saveStatusList) {
            APIIntegration.CONNECT.savePersonnelRequest inValue = new APIIntegration.CONNECT.savePersonnelRequest();
            inValue.personnelRecords = personnelRecords;
            inValue.extension = extension;
            APIIntegration.CONNECT.savePersonnelResponse retVal = ((APIIntegration.CONNECT.HumanResourcesInboundServiceSoap)(this)).savePersonnel(inValue);
            extension = retVal.extension;
            saveStatusList = retVal.saveStatusList;
            return retVal.savePersonnelResult;
        }
        
        public System.Threading.Tasks.Task<APIIntegration.CONNECT.savePersonnelResponse> savePersonnelAsync(APIIntegration.CONNECT.savePersonnelRequest request) {
            return base.Channel.savePersonnelAsync(request);
        }
    }
}
